def getTVForTeam(away: str) -> str: ...
def fetchTV(event: str, away): ...
def store(week, away, home, event: str = "N/A") -> None: ...
def parseAndStore() -> None: ...
def fetchGames(week) -> None: ...
def processSchedule() -> Schedule.Schedule: ...
def fetchCrews() -> None: ...
