
class CrewInfo:
    def __init__(self) -> None: ...
    def fetchCrewInfo(self) -> None: ...
    def updateCrew(self, crewName, game) -> None: ...
    def assignOff(self, crewName, week) -> None: ...
