
class Schedule:
    def __init__(self) -> None: ...
    def runTest(self) -> None: ...
    def printAllCrews(self) -> None: ...
    def printGamesForWeek(self, week) -> None: ...
    def printGamesForCrew(self, crewName) -> None: ...
    def loadCrews(self) -> CrewInfo.CrewInfo: ...
    def loadGames(self) -> GameInfo.GameInfo: ...
    def processSchedule(self) -> None: ...
    def findBestCrew(self, crewList, week, away, home, primetime=None): ...
    def updateCrewSchedule(self, crewName, week, game) -> None: ...
